### ISSUE TITLE
Very bad performance of JRuby 1.7.4

### ISSUE THREAD

**Issue by adriantoman** [koraktor/rbzip2#2]
I am trying to use this gem under JRuby 1.7.4 for decompressing file compressed in bzip2. 

The size of compressed file is 422Kb. The decompressed file have 7.9M. Decompression by bzip2 in Linux take less than 1s.

When I am using the gem, the part of code  RBzip2::Decompressor.new file take around 30s and the read part take more than 30mins ( yes minutes ). During the decompression Jruby process is taking 100% of one core on my PC. I am running it on Fedora 16. Java version 1.7.0.

**Comment by koraktor** [comment]
Closing this. Please reopen if you still see bad performance with version 0.3.0 (and Commons Compress).
