### ISSUE TITLE
RBZip2 never finishes on large file

### ISSUE THREAD

**Issue by rylarson** [koraktor/rbzip2#3]
Even for a moderately large file, RBzip2::Decompressor.new never returns, because it seems to sit endlessly in `get_and_move_to_front_decode`. 

Code snippet that reproduces the problem (on linux)

```
#!/usr/bin/env ruby

`dd if=/dev/urandom of=output.dat bs=1M count=10`
`tar cjvf bigTar.tar.bz2 output.dat`
require 'rbzip2'
dc = RBzip2::Decompressor.new(File.new('bigTar.tar.bz2'))
```

**Comment by koraktor** [comment]
Sorry for the late response.

Can you provide a stacktrace or dump? I didn't find time to reproduce this, yet.

**Comment by rylarson** [comment]
There is no stacktrace, it never finishes. If you run those 4 lines of code I posted, it will exhibit the behavior.

**Comment by koraktor** [comment]
You’re right. 0.2.0 hangs for such a file.

Please try the code on `master`, it works for me.

**Comment by taylorfinnell** [comment]
Is it possible to get a RubyGems release if master is more functional?

**Comment by koraktor** [comment]
@taylorfinnell Sorry for another delay.

Did you test the `master` code? I never got a response from @rylarson, so I'm still not confident that this fixes the problem. Additionally the code base has been stale for quite some time, so it might take a while to release a more or less stable gem.

**Comment by rylarson** [comment]
Hey there,

Sorry for the delay. I did try the code on master, it doesn't hang anymore but I get a CRC error:

```
 => #<RBzip2::Ruby::Decompressor: @io=#<File:bigTar.tar.bz2> size=10043871 uncompressed=899981> 
2.3.1 :012 > dc.read
RuntimeError: BZip2 CRC error
	from /Users/rjlarson/working/rbzip2/lib/rbzip2/ruby/decompressor.rb:148:in `complete'
	from /Users/rjlarson/working/rbzip2/lib/rbzip2/ruby/decompressor.rb:111:in `init_block'
	from /Users/rjlarson/working/rbzip2/lib/rbzip2/ruby/decompressor.rb:599:in `setup_no_rand_part_a'
	from /Users/rjlarson/working/rbzip2/lib/rbzip2/ruby/decompressor.rb:674:in `setup_no_rand_part_c'
	from /Users/rjlarson/working/rbzip2/lib/rbzip2/ruby/decompressor.rb:66:in `read0'
	from /Users/rjlarson/working/rbzip2/lib/rbzip2/ruby/decompressor.rb:40:in `read'
	from (irb):12
	from /Users/rjlarson/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```

**Comment by koraktor** [comment]
I was finally able to track this down. Thanks.
