### ISSUE TITLE
New version release?

### ISSUE THREAD

**Issue by dmorrill10** [koraktor/rbzip2#4]
The most recently released version of this gem on Rubygems is `0.2.0`. I'd like to use this gem as a dependency in [BrickAndMortar](https://github.com/dmorrill10/brick_and_mortar) but I can't get `0.2.0` to work.  The current commit, f8ab1eaa991537c0bb2f5e9bd1f52e73b1f9351e, seems to work just fine for me (decompression only). 

Is someone working on making a new release soon, or could I help to accomplish this?

If you're concerned about the gem not being stable enough yet, how about a release candidate version like `0.3.0-rc1`?

**Comment by dmorrill10** [comment]
At least for now, I'm using [bzip2-ffi](https://github.com/philr/bzip2-ffi), so there's no rush on this.

**Comment by koraktor** [comment]
Did you experience problems with compression or do you just not have a use case for this?

Development had stalled quite a while now. I’ll have a look at #1 first. But if it’s too hard to implement quickly I guess there’s no reason to hold back the release of 0.3.0.

**Comment by dmorrill10** [comment]
No use case, I just need decompression.

Okay, sure. This library is nice in that it drops down to a Ruby implementation without FFI. But, like I said, I do have an alternative working, so no rush.

**Comment by taylorfinnell** [comment]
I too would be interested in a release or RC! +1

**Comment by koraktor** [comment]
Finally… [0.3.0](https://github.com/koraktor/rbzip2/releases/tag/0.3.0) is here.
